spring.application.name=49-SB-Jwt-App

spring.security.user.name=Ayush
spring.security.user.password=Ayush123@

# Data source properties
spring.datasource.url=jdbc:mysql://localhost:3306/SPRINGBOOT
spring.datasource.username=root
spring.datasource.password=Ayush123@

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# JWT properties
spring.app.jwt.secret=mySecretKey123912738dggvsgsvdfgdfgddfhdhdfhdfhdfhfdhdfassffdggfhjghkjlks
spring.app.jwt.expiration=3000000

logging.level.org.springframework=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.security=DEBUG