spring.application.name=39-FileUploadDownload

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

file.upload-dir=/Users/Ayush/Desktop/DESKTOP FOLDERS/Study Material/SBMS
