FROM openjdk:17
MAINTAINER "Ayush Kumar Singh <797979>"
COPY target/17-RESTAPI-FirstApp-0.0.1-SNAPSHOT.jar  /usr/app/
WORKDIR /usr/app/
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "17-RESTAPI-FirstApp-0.0.1-SNAPSHOT.jar"]
